### ISSUE TITLE
ThankfulThoughts

### ISSUE THREAD

**Issue by hqasmei** [chronark/starlog#2]
**What is your project about**
ThankfulThoughts is a web application that allows users to input a person, place, or thing, and generates a sentence of gratitude in return. It's a simple yet powerful tool to help users express gratitude and positive thoughts towards the things they are thankful for.

**GitHub Link**
https://github.com/hqasmei/thankful-thoughts

**Public URL**
https://thankfulthoughts.io/

**Comment by chronark** [comment]
Hey @hqasmei ,this is great
can you add your twitter handle
I should've added that in the template :D

Also a README with instruction how to run and deploy it would be great

**Comment by hqasmei** [comment]
My twitter handle is @hqasmei 
And I should've included readme instructions. Let me know if you need anything else. Thank you!
